# GitHub Sponsors and funding platforms for Nbiish's repositories
# This file enables the "Sponsor" button on GitHub repositories

github: [nbiish]  # GitHub Sponsors username
ko_fi: nbiish     # Ko-fi username  
# patreon: nbiish # Uncomment when Patreon is set up
# open_collective: nbiish # Uncomment when Open Collective is set up
# tidelift: # Add Tidelift package name when applicable
# community_bridge: # Add Community Bridge project name when applicable
# liberapay: nbiish # Uncomment when Liberapay is set up
# issuehunt: nbiish # Uncomment when IssueHunt is set up
custom: [
  "https://raw.githubusercontent.com/nbiish/license-for-all-works/8e9b73b269add9161dc04bbdd79f818c40fca14e/qr-stripe-donation.png",
  "https://www.buymeacoffee.com/nbiish"
]